apiVersion: apps/v1
kind: Deployment

metadata:
  name: house-service-deploy
  namespace: hotketok

spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-service

  template:
    metadata:
      labels:
        app: house-service
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: house-service
          image: contest57-registry-real.kr.ncr.ntruss.com/hotketok/hotketok-house-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/

          envFrom:
            - secretRef:
                name: house-service-secret
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: house-service-config