apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: hotketok
data:
  application-prod.yml: |
    server:
      port: 8000
    
    spring:
      application:
        name: api-gateway-service
      cloud:
        kubernetes:
          discovery:
            enabled: true
            all-namespaces: true   
          config:
            enabled: true
            sources:
              - namespace: hotketok
                name: api-gateway-config
            
        loadbalancer:
          enabled: true
        
        gateway:
          auto-discovery:
            enabled: false
            
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth-service/**
                - Method=GET,POST,PUT,DELETE
     
            - id: requestform-service
              uri: lb://requestform-service
              predicates:
                - Path=/api/requestform-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - JwtAuthFilter
                - name: RoleFilter
                  args:
                    allowedRoles:
                      - OWNER
                      - TENANT
     
            - id: chatting-service
              uri: lb://chatting-service
              predicates:
                - Path=/api/chatting-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - JwtAuthFilter
                - name: RoleFilter
                  args:
                    allowedRoles:
                      - OWNER
                      - TENANT
                      - VENDOR
     
            - id: infra-service
              uri: lb://infra-service
              predicates:
                - Path=/api/infra-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - JwtAuthFilter
                - name: RoleFilter
                  args:
                    allowedRoles:
                      - NONE
                      - OWNER
                      - TENANT
     
            - id: house-service
              uri: lb://house-service
              predicates:
                - Path=/api/house-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - JwtAuthFilter
                - name: RoleFilter
                  args:
                    allowedRoles:
                      - NONE
                      - OWNER
                      - TENANT
                      - VENDOR
     
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/user-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - JwtAuthFilter
                - name: RoleFilter
                  args:
                    allowedRoles:
                      - NONE
                      - OWNER
                      - TENANT
                      - VENDOR
     
            - id: commonbill-service
              uri: lb://commonbill-service
              predicates:
                - Path=/api/commonbill-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - JwtAuthFilter
                - name: RoleFilter
                  args:
                    allowedRoles:
                      - OWNER
                      - TENANT
                      
            - id: vendor-service
              uri: lb://vendor-service
              predicates:
                - Path=/api/vendor-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - JwtAuthFilter
                - name: RoleFilter
                  args:
                    allowedRoles:
                      - NONE
                      - OWNER
                      - TENANT
                      - VENDOR
            
            - id: estimate-service
              uri: lb://estimate-service
              predicates:
                - Path=/api/estimate-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - JwtAuthFilter
                - name: RoleFilter
                  args:
                    allowedRoles:
                      - OWNER
                      - TENANT
                      - VENDOR
    
    jwt:
      secret: ${JWT_SECRET}
      
    eureka:
      client:
        enabled: false
        
    management:
      endpoints:
        web:
          exposure:
            include: health,info,discoveryclients
      endpoint:
        health:
          show-details: always