apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: hotketok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: api-gateway-service
          image: hotketok-reg-real.kr.ncr.ntruss.com/hotketok/hotketok-api-gateway-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: SPRING_CONFIG_LOCATION
              value: file:/config/
          envFrom:
            - secretRef:
                name: api-gateway-secret
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-config