apiVersion: v1
kind: ConfigMap
metadata:
  name: chatting-service-config
  namespace: hotketok
data:
  application-prod.yml: |
    server:
      port: 8096
    
    spring:
      application:
        name: chatting-service
      
      datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:chatting}?serverTimezone=Asia/Seoul
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
      
      cloud:
        kubernetes:
          discovery:
            enabled: true
            all-namespaces: true
          config:
            enabled: true
            sources:
              - namespace: hotketok
                name: chatting-service-config
    eureka:
      client:
        enabled: false
        
    logging:
      level:
        org.hibernate.SQL: debug

    client:
      requestform-service:
        url: http://localhost:8093
      user-service:
        url: http://localhost:8088
      vendor-service:
        url: http://localhost:8099
      house-service:
        url: http://localhost:8090
