apiVersion: v1
kind: ConfigMap
metadata:
  name: estimate-service-config
  namespace: hotketok
data:
  application-prod.yml: |
    server:
      port: 8094

    spring:
      datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:estimate}?serverTimezone=Asia/Seoul
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

      cloud:
        kubernetes:
          discovery:
            enabled: true
            all-namespaces: true

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            
    eureka:
      client:
        enabled: false
        
    client:
      requestform-service:
        url: http://requestform-service.hotketok.svc.cluster.local:8093
      vendor-service:
        url: http://vendor-service.hotketok.svc.cluster.local:8099