apiVersion: apps/v1
kind: Deployment

metadata:
  name: estimate-service-deploy
  namespace: hotketok

spec:
  replicas: 1
  selector:
    matchLabels:
      app: estimate-service

  template:
    metadata:
      labels:
        app: estimate-service
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: estimate-service
          image: contest57-registry-real.kr.ncr.ntruss.com/hotketok/hotketok-estimate-service:latest
          ports:
            - containerPort: 8094
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/
          envFrom:
            - secretRef:
                name: estimate-service-secret
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: estimate-service-config