apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service-deploy
  namespace: hotketok

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: auth-service
          image: hotketok-reg-real.kr.ncr.ntruss.com/hotketok/hotketok-auth-service:latest
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/

          envFrom:
            - secretRef:
                name: auth-service-secret
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: auth-service-config