apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: hotketok
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8087
      targetPort: 8087