apiVersion: apps/v1
kind: Deployment

metadata:
  name: infra-service-deploy
  namespace: hotketok

spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-service

  template:
    metadata:
      labels:
        app: infra-service
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: infra-service
          image: hotketok-reg-real.kr.ncr.ntruss.com/hotketok/hotketok-infra-service:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/
          envFrom:
            - secretRef:
                name: infra-service-secret
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: infra-service-config